# Pengujian Confusion Matrics Pada Metode SAW

## Menambahkan Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [2]:
df_true = pd.read_csv('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_skor_kategori_aktual.csv')
df_pred = pd.read_csv('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_skor_kategori_prediksi.csv')

## Data Aktual

In [3]:
df_y = df_true['kategori']
y_true = df_y.to_numpy()
y_true

array(['ahli', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli', 'pemula',
       'menengah', 'ahli', 'pemula', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'pemula', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'pemula', 'pemula',
       'menengah', 'ahli', 'pemula', 'menengah', 'ahli', 'pemula',
       'menengah', 'ahli', 'pemula', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'pemula', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'pemula', 'pemula',
       'menengah', 'ahli', 'pemula', 'menengah', 'ahli', 'pemula',
       'menengah', 'ahli', 'menengah', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'menengah', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'me

## Data Prediksi

In [4]:
df_yt = df_pred['kategori']
y_pred = df_yt.to_numpy()
y_pred

array(['pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'pemula', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'pemula', 'pemula',
       'menengah', 'ahli', 'pemula', 'menengah', 'ahli', 'pemula',
       'menengah', 'ahli', 'pemula', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'menengah', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli', 'menengah', 'pemula',
       'menengah', 'ahli', 'pemula', 'menengah', 'ahli', 'pemula',
       'menengah', 'ahli', 'menengah', 'pemula', 'menengah', 'ahli',
       'pemula', 'menengah', 'ahli', 'pemula', 'menengah', 'ahli',
       'menengah', 'pemula', 'menengah', 'ahli', 'pemula', 'menengah',
       'ahli', 'pemula', 'menengah', 'ahli

## Hasil Prediksi Metode SAW

In [5]:
dt = confusion_matrix(y_true, y_pred, labels=['pemula','menengah','ahli'])

In [7]:
tabel = pd.DataFrame(dt)
dt

array([[32,  3,  0],
       [ 0, 33,  1],
       [ 1,  0, 30]])

## Menghitung Nilai Accuracy, Precision, dan Recall

In [8]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
#confution matrix
cm = confusion_matrix(y_true, y_pred)
print("CONFUSION MATRIX")
print(cm)
akurasi=classification_report(y_true, y_pred)
print("ACCURACY Simple Additive Weighting ")
print("Accuracy :", akurasi)
akurasi=accuracy_score(y_true, y_pred)
print("Tingkat : akurasi : {:.2%}".format(akurasi))

CONFUSION MATRIX
[[30  0  1]
 [ 1 33  0]
 [ 0  3 32]]
ACCURACY Simple Additive Weighting 
Accuracy :               precision    recall  f1-score   support

        ahli       0.97      0.97      0.97        31
    menengah       0.92      0.97      0.94        34
      pemula       0.97      0.91      0.94        35

    accuracy                           0.95       100
   macro avg       0.95      0.95      0.95       100
weighted avg       0.95      0.95      0.95       100

Tingkat : akurasi : 95.00%
