In [231]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Identifikasi Variabel

In [232]:
df_alt = pd.read_csv ('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_player_aktual.csv')

In [233]:
alt = df_alt['ID Pemain']

In [234]:
alternatif = alt.to_numpy()

In [235]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [236]:
kriteria = ['c1','c2','c3','c4','c5','c6','c7','c8']

In [237]:
costbenefit = ['benefit','benefit','benefit','benefit','benefit','benefit','benefit','benefit']

In [238]:
kepentingan = [3,3,4,4,3,2,1,4]

In [239]:
alternatifkriteria = df_alt[['C1','C2','C3','C4','C5','C6','C7','C8']].to_numpy()
alternatifkriteria

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 100,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [240]:
print(str(kriteria))

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8']


In [241]:
print(str(costbenefit))

['benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit']


In [242]:
print(str(kepentingan))

[3, 3, 4, 4, 3, 2, 1, 4]


In [243]:
print(str(alternatifkriteria))

[[100 100 100 100 100 100 100 100]
 [ 60  40  40  40  60  60  40  60]
 [ 80  60  80  80  80  80  80  80]
 [ 21  60  21  21  21  21  21  21]
 [ 61 100  41  41  61  61  41  61]
 [ 81  21  81  81  81  81  81  81]
 [ 22  41  22  22  22  22  22  22]
 [ 62  61  42  42  62  62  42  62]
 [ 82  61  82  82  82  82  82  82]
 [ 23 100  23  23  23  23  23  23]
 [ 21  22  21  21  21  21  21  21]
 [ 61  42  41  41  61  61  41  61]
 [ 81  62  81  81  81  81  81  81]
 [ 22  62  22  22  22  22  22  22]
 [ 62 100  42  42  62  62  42  62]
 [ 82  23  82  82  82  82  82  82]
 [ 23  43  23  23  23  23  23  23]
 [ 63  63  43  43  63  63  43  63]
 [ 83  63  83  83  83  83  83  83]
 [ 24 100  24  24  24  24  24  24]
 [ 22  24  22  22  22  22  22  22]
 [ 62  44  42  42  62  62  42  62]
 [ 82  64  82  82  82  82  82  82]
 [ 23  64  23  23  23  23  23  23]
 [ 63 100  43  43  63  63  43  63]
 [ 83  25  83  83  83  83  83  83]
 [ 24  45  24  24  24  24  24  24]
 [ 64  65  44  44  64  64  44  64]
 [ 84  65  84  84  8

In [244]:
pembagi = []

In [245]:
for i in range(len(kriteria)):
    pembagi.append(0)
    for j in range(len(alternatif)):
        if costbenefit[i] == 'cost':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] > alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] < alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]

In [246]:
print(str(pembagi))

[100, 100, 100, 100, 100, 100, 100, 100]


## Tahap Normalisasi

In [247]:
normalisasi = []

In [248]:
for i in range(len(alternatif)):
    normalisasi.append([])
    for j in range(len(kriteria)):
        normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            normalisasi[i][j] = pembagi[j] / alternatifkriteria[i][j]
        else: #if costbenefit[j] == 'benefit':
            normalisasi[i][j] = alternatifkriteria[i][j] / pembagi[j]

In [249]:
print(str(normalisasi))

[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.6, 0.4, 0.4, 0.4, 0.6, 0.6, 0.4, 0.6], [0.8, 0.6, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8], [0.21, 0.6, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21], [0.61, 1.0, 0.41, 0.41, 0.61, 0.61, 0.41, 0.61], [0.81, 0.21, 0.81, 0.81, 0.81, 0.81, 0.81, 0.81], [0.22, 0.41, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22], [0.62, 0.61, 0.42, 0.42, 0.62, 0.62, 0.42, 0.62], [0.82, 0.61, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82], [0.23, 1.0, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23], [0.21, 0.22, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21], [0.61, 0.42, 0.41, 0.41, 0.61, 0.61, 0.41, 0.61], [0.81, 0.62, 0.81, 0.81, 0.81, 0.81, 0.81, 0.81], [0.22, 0.62, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22], [0.62, 1.0, 0.42, 0.42, 0.62, 0.62, 0.42, 0.62], [0.82, 0.23, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82], [0.23, 0.43, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23], [0.63, 0.63, 0.43, 0.43, 0.63, 0.63, 0.43, 0.63], [0.83, 0.63, 0.83, 0.83, 0.83, 0.83, 0.83, 0.83], [0.24, 1.0, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24], [0.22, 0.24, 0.22, 0.22, 0.2

In [250]:
hasil = []

In [251]:
for i in range(len(alternatif)):
    hasil.append(0)
    for j in range(len(kriteria)):
        hasil[i] = hasil[i] + (normalisasi[i][j] * kepentingan[j])

## Hasil Skor Nilai

In [252]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [253]:
print(str(hasil))

[24.0, 12.0, 18.6, 6.209999999999999, 14.01, 17.64, 5.85, 13.05, 19.05, 7.830000000000001, 5.069999999999999, 12.27, 18.87, 6.48, 14.219999999999999, 17.91, 6.12, 13.319999999999999, 19.32, 8.04, 5.34, 12.54, 19.14, 6.750000000000001, 14.43, 18.18, 6.39, 13.589999999999998, 19.59, 8.25, 5.61, 12.809999999999999, 19.41, 7.0200000000000005, 14.639999999999999, 18.45, 6.66, 13.860000000000001, 19.86, 8.46, 5.88, 13.08, 19.68, 7.29, 14.85, 18.72, 6.930000000000001, 14.13, 20.130000000000003, 8.670000000000002, 6.15, 13.35, 19.95, 7.56, 15.060000000000002, 18.99, 7.200000000000001, 14.4, 20.400000000000002, 8.88, 6.420000000000001, 13.620000000000001, 20.220000000000002, 7.830000000000002, 15.27, 19.259999999999998, 7.470000000000001, 14.67, 20.669999999999998, 9.09, 6.690000000000001, 13.89, 20.490000000000002, 8.1, 15.479999999999999, 19.53, 7.74, 14.940000000000001, 20.94, 9.299999999999999, 6.960000000000001, 14.160000000000002, 20.759999999999998, 8.370000000000001, 15.690000000000001,

## Tabel Skor Nilai

In [254]:
data_skor = ({'ID_Pemain':(alternatif),'nilai':(hasil)})

In [255]:
df_skor = pd.DataFrame(data_skor)

## Kesimpulan jika nilai < 9 (pemula), 9-17(menengah), dan >17(ahli)

In [256]:
df_n = df_skor['nilai']
n =  df_n.to_numpy()
ktr = []
def hasil():
    for i in n:
        if i < 9:
            ktr.append('pemula')
        elif i >= 9 and i <= 17:
            ktr.append('menengah')
        else :
            ktr.append('ahli')

hasil()

In [257]:
df_skor.insert(2, 'kriteria', ktr, True)

In [258]:
display(df_skor)

ID_Pemain  nilai  kriteria
0       25601  24.00      ahli
1       25602  12.00  menengah
2       25603  18.60      ahli
3       25604   6.21    pemula
4       25605  14.01  menengah
..        ...    ...       ...
95      25696  20.07      ahli
96      25697   8.28    pemula
97      25698  15.48  menengah
98      25699  21.48      ahli
99      25700   9.72  menengah

[100 rows x 3 columns]

In [259]:
df_skor.to_csv('data_skor&kriteria_aktual.csv')

## Hitung Akurasi

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

## Membagi data x_test dan y_test

In [224]:
xalt = df_alt.loc[0:49, 'ID Pemain']
x_alt = xalt.to_numpy()

In [225]:
x = df_alt.loc[0:49, 'C1':'C8']
x_test = x.to_numpy()
x_test

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 100,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [226]:
yalt = df_alt.loc[0:49, 'ID Pemain']
y_alt = yalt.to_numpy()
y = df_alt.loc[50:100, 'C1':'C8']
y_test = y.to_numpy()
y_test

array([[ 25,  30,  25,  25,  25,  25,  25,  25],
       [ 65,  50,  45,  45,  65,  65,  45,  65],
       [ 85,  70,  85,  85,  85,  85,  85,  85],
       [ 26,  70,  26,  26,  26,  26,  26,  26],
       [ 66, 100,  46,  46,  66,  66,  46,  66],
       [ 86,  31,  86,  86,  86,  86,  86,  86],
       [ 27,  51,  27,  27,  27,  27,  27,  27],
       [ 67,  71,  47,  47,  67,  67,  47,  67],
       [ 87,  71,  87,  87,  87,  87,  87,  87],
       [ 28, 100,  28,  28,  28,  28,  28,  28],
       [ 26,  32,  26,  26,  26,  26,  26,  26],
       [ 66,  52,  46,  46,  66,  66,  46,  66],
       [ 86,  72,  86,  86,  86,  86,  86,  86],
       [ 27,  72,  27,  27,  27,  27,  27,  27],
       [ 67, 100,  47,  47,  67,  67,  47,  67],
       [ 87,  33,  87,  87,  87,  87,  87,  87],
       [ 28,  53,  28,  28,  28,  28,  28,  28],
       [ 68,  73,  48,  48,  68,  68,  48,  68],
       [ 88,  73,  88,  88,  88,  88,  88,  88],
       [ 29, 100,  29,  29,  29,  29,  29,  29],
       [ 27,  34,  2

In [227]:
x_pembagi = []

In [228]:
for i in range(len(kriteria)):
    x_pembagi.append(0)
    for j in range(len(x_alt)):
        if costbenefit[i] == 'cost':
            if j == 0:
                x_pembagi[i] = x_test[j][i]
            else:
                if x_pembagi[i] > x_test[j][i]:
                    x_pembagi[i] = x_test[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                x_pembagi[i] = x_test[j][i]
            else:
                if x_pembagi[i] < x_test[j][i]:
                    x_pembagi[i] = x_test[j][i]

In [229]:
print(str(x_pembagi))

[100, 100, 100, 100, 100, 100, 100, 100]


In [230]:
y_pembagi = []

In [159]:
for i in range(len(kriteria)):
    y_pembagi.append(0)
    for j in range(len(x_alt)):
        if costbenefit[i] == 'cost':
            if j == 0:
                y_pembagi[i] = x_test[j][i]
            else:
                if y_pembagi[i] > x_test[j][i]:
                    y_pembagi[i] = x_test[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                y_pembagi[i] = x_test[j][i]
            else:
                if y_pembagi[i] < x_test[j][i]:
                    y_pembagi[i] = x_test[j][i]

In [160]:
x_normalisasi = []

In [169]:
for i in range(len(x_alt)):
    x_normalisasi.append([])
    for j in range(len(kriteria)):
        x_normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            x_normalisasi[i][j] = x_pembagi[j] / x_test[i][j]
        else: #if costbenefit[j] == 'benefit':
            x_normalisasi[i][j] = x_test[i][j] / x_pembagi[j]

In [170]:
y_normalisasi = []

In [171]:
for i in range(len(y_alt)):
    y_normalisasi.append([])
    for j in range(len(kriteria)):
        y_normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            y_normalisasi[i][j] = y_pembagi[j] / y_test[i][j]
        else: #if costbenefit[j] == 'benefit':
            y_normalisasi[i][j] = y_test[i][j] / y_pembagi[j]

In [164]:
x_hasil = []

In [165]:
for i in range(len(x_test)):
    x_hasil.append(0)
    for j in range(len(kriteria)):
        x_hasil[i] = x_hasil[i] + (x_normalisasi[i][j] * kepentingan[j])

In [174]:
y_hasil = []

In [175]:
for i in range(len(y_test)):
    y_hasil.append(0)
    for j in range(len(kriteria)):
        y_hasil[i] = y_hasil[i] + (y_normalisasi[i][j] * kepentingan[j])

In [166]:
x_pred = ({'ID Pemain':(x_alt),'nilai':(x_hasil)})

In [167]:
df_x_pred = pd.DataFrame(x_pred)
display(df_x_pred)

ID Pemain      nilai
0       25601   5.477780
1       25602  13.746258
2       25603  21.317062
3       25604   6.910085
4       25605  15.772623
5       25606  20.402832
6       25607   6.589915
7       25608  14.858393
8       25609  21.835137
9       25610   8.616279
10      25611   5.781372
11      25612  14.049850
12      25613  21.620654
13      25614   7.213677
14      25615  16.016809
15      25616  20.706424
16      25617   6.893507
17      25618  15.161985
18      25619  22.138729
19      25620   8.830762
20      25621   6.084964
21      25622  14.353442
22      25623  21.924246
23      25624   7.517269
24      25625  16.260995
25      25626  21.010016
26      25627   7.197099
27      25628  15.465577
28      25629  22.442321
29      25630   9.074948
30      25631   6.388556
31      25632  14.657034
32      25633  22.227838
33      25634   7.820861
34      25635  16.505181
35      25636  21.313608
36      25637   7.500691
37      25638  15.769169
38      25639  22.745913
39      25640   9.319134
40      25641   6.692148
41      25642  14.960626
42      25643  22.531430
43      25644   8.124453
44      25645  16.749367
45      25646  21.617200
46      25647   7.804283
47      25648  16.072761
48      25649  23.049505
49      25650   9.563320

In [177]:
y_pred = ({'ID Pemain':(y_alt),'nilai':(y_hasil)})

In [1]:
df_y_pred = pd.DataFrame(y_pred)
# display(df_y_pred)

NameError: name 'pd' is not defined

In [179]:
df_alt

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
0       25601  20   20  20  20  20  20  20  20    20
1       25602  60   40  40  40  60  60  40  60    60
2       25603  80   60  80  80  80  80  80  80    80
3       25604  21   60  21  21  21  21  21  21    21
4       25605  61  100  41  41  61  61  41  61    61
..        ...  ..  ...  ..  ..  ..  ..  ..  ..   ...
95      25696  90   39  90  90  90  90  90  90    90
96      25697  31   59  31  31  31  31  31  31    31
97      25698  71   79  51  51  71  71  51  71    71
98      25699  91   79  91  91  91  91  91  91    91
99      25700  32  100  32  32  32  32  32  32    32

[100 rows x 10 columns]

In [242]:
df_alt.shape

(100, 10)

In [251]:
proposisi = 0.7
df_1 = df_alt.sample(frac=proposisi)
df_2 = df_alt.drop(df_1.index)

print (f'df_1 shape = {df_1.shape}')
print (f'df_2 shape = {df_2.shape}')

df_1 shape = (70, 10)
df_2 shape = (30, 10)


In [252]:
df_1

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
81      25682  68   56  48  48  68  68  48  68    68
3       25604  21   60  21  21  21  21  21  21    21
29      25630  25  100  25  25  25  25  25  25    25
43      25644  25   68  25  25  25  25  25  25    25
33      25634  24   66  24  24  24  24  24  24    24
..        ...  ..  ...  ..  ..  ..  ..  ..  ..   ...
21      25622  62   44  42  42  62  62  42  62    62
67      25668  68   73  48  48  68  68  48  68    68
73      25674  28   74  28  28  28  28  28  28    28
0       25601  20   20  20  20  20  20  20  20    20
78      25679  89   75  89  89  89  89  89  89    89

[70 rows x 10 columns]

In [253]:
df_2

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
1       25602  60   40  40  40  60  60  40  60    60
5       25606  81   21  81  81  81  81  81  81    81
6       25607  22   41  22  22  22  22  22  22    22
9       25610  23  101  23  23  23  23  23  23    23
14      25615  62  100  42  42  62  62  42  62    62
22      25623  82   64  82  82  82  82  82  82    82
25      25626  83   25  83  83  83  83  83  83    83
27      25628  64   65  44  44  64  64  44  64    64
28      25629  84   65  84  84  84  84  84  84    84
31      25632  63   46  43  43  63  63  43  63    63
36      25637  25   47  25  25  25  25  25  25    25
38      25639  85   67  85  85  85  85  85  85    85
39      25640  26  100  26  26  26  26  26  26    26
40      25641  24   28  24  24  24  24  24  24    24
46      25647  26   49  26  26  26  26  26  26    26
47      25648  66   69  46  46  66  66  46  66    66
51      25652  65   50  45  45  65  65  45  65    65
52      25653  85   70  85  85  85  85  85  85    85
62      25663  86   72  86  86  86  86  86  86    86
65      25666  87   33  87  87  87  87  87  87    87
72      25673  87   74  87  87  87  87  87  87    87
82      25683  88   76  88  88  88  88  88  88    88
83      25684  29   76  29  29  29  29  29  29    29
84      25685  69  100  49  49  69  69  49  69    69
85      25686  89   37  89  89  89  89  89  89    89
87      25688  70   77  50  50  70  70  50  70    70
89      25690  31  100  31  31  31  31  31  31    31
91      25692  69   58  49  49  69  69  49  69    69
93      25694  30   78  30  30  30  30  30  30    30
94      25695  70  100  50  50  70  70  50  70    70