In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Identifikasi Variabel

In [168]:
df_alt = pd.read_csv ('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_player.csv')

In [169]:
alt = df_alt['ID Pemain']

In [170]:
alternatif = alt.to_numpy()

In [171]:
print(str(alternatif))
# alternatif.info()
# alternatif.describe()

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610]


In [172]:
kriteria = ['c1','c2','c3','c4','c5','c6','c7','c8']

In [173]:
costbenefit = ['benefit','benefit','benefit','benefit','benefit','benefit','benefit','benefit']

In [174]:
kepentingan = [3,3,4,4,3,2,1,4]

In [175]:
alternatifkriteria = df_alt[['C1','C2','C3','C4','C5','C6','C7','C8']].to_numpy()
alternatifkriteria

array([[ 20,  20,  20,  20,  20,  20,  20,  20],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  80,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81, 120,  81,  81,  81,  81,  81,  81],
       [ 22, 140,  22,  22,  22,  22,  22,  22],
       [ 62, 160,  42,  42,  62,  62,  42,  62],
       [ 82, 180,  82,  82,  82,  82,  82,  82],
       [ 23, 200,  23,  23,  23,  23,  23,  23]])

In [176]:
print(str(kriteria))

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8']


In [177]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610]


In [178]:
print(str(costbenefit))

['benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit']


In [179]:
print(str(kepentingan))

[3, 3, 4, 4, 3, 2, 1, 4]


In [180]:
print(str(alternatifkriteria))

[[ 20  20  20  20  20  20  20  20]
 [ 60  40  40  40  60  60  40  60]
 [ 80  60  80  80  80  80  80  80]
 [ 21  80  21  21  21  21  21  21]
 [ 61 100  41  41  61  61  41  61]
 [ 81 120  81  81  81  81  81  81]
 [ 22 140  22  22  22  22  22  22]
 [ 62 160  42  42  62  62  42  62]
 [ 82 180  82  82  82  82  82  82]
 [ 23 200  23  23  23  23  23  23]]


In [181]:
pembagi = []

In [182]:
for i in range(len(kriteria)):
    pembagi.append(0)
    for j in range(len(alternatif)):
        if costbenefit[i] == 'cost':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] > alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] < alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]

In [183]:
print(str(pembagi))

[82, 200, 82, 82, 82, 82, 82, 82]


## Tahap Normalisasi

In [184]:
normalisasi = []

In [185]:
for i in range(len(alternatif)):
    normalisasi.append([])
    for j in range(len(kriteria)):
        normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            normalisasi[i][j] = pembagi[j] / alternatifkriteria[i][j]
        else: #if costbenefit[j] == 'benefit':
            normalisasi[i][j] = alternatifkriteria[i][j] / pembagi[j]

In [186]:
print(str(normalisasi))

[[0.24390243902439024, 0.1, 0.24390243902439024, 0.24390243902439024, 0.24390243902439024, 0.24390243902439024, 0.24390243902439024, 0.24390243902439024], [0.7317073170731707, 0.2, 0.4878048780487805, 0.4878048780487805, 0.7317073170731707, 0.7317073170731707, 0.4878048780487805, 0.7317073170731707], [0.975609756097561, 0.3, 0.975609756097561, 0.975609756097561, 0.975609756097561, 0.975609756097561, 0.975609756097561, 0.975609756097561], [0.25609756097560976, 0.4, 0.25609756097560976, 0.25609756097560976, 0.25609756097560976, 0.25609756097560976, 0.25609756097560976, 0.25609756097560976], [0.7439024390243902, 0.5, 0.5, 0.5, 0.7439024390243902, 0.7439024390243902, 0.5, 0.7439024390243902], [0.9878048780487805, 0.6, 0.9878048780487805, 0.9878048780487805, 0.9878048780487805, 0.9878048780487805, 0.9878048780487805, 0.9878048780487805], [0.2682926829268293, 0.7, 0.2682926829268293, 0.2682926829268293, 0.2682926829268293, 0.2682926829268293, 0.2682926829268293, 0.2682926829268293], [0.75609

In [187]:
hasil = []

In [188]:
for i in range(len(alternatif)):
    hasil.append(0)
    for j in range(len(kriteria)):
        hasil[i] = hasil[i] + (normalisasi[i][j] * kepentingan[j])

## Hasil Skor Nilai

In [189]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610]


In [190]:
print(str(hasil))

[5.421951219512196, 13.770731707317072, 21.38780487804878, 6.578048780487806, 14.926829268292682, 22.543902439024393, 7.734146341463415, 16.082926829268292, 23.7, 8.890243902439025]


## Tabel Skor Nilai

In [191]:
data_skor = ({'ID_Pemain':(alternatif),'nilai':(hasil)})

In [192]:
df_skor = pd.DataFrame(data_skor)
display(df_skor)

ID_Pemain      nilai
0      25601   5.421951
1      25602  13.770732
2      25603  21.387805
3      25604   6.578049
4      25605  14.926829
5      25606  22.543902
6      25607   7.734146
7      25608  16.082927
8      25609  23.700000
9      25610   8.890244