# Data Pemain Game Mobile Legends Prediksi

## Menambahkan Library

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Mengidentifikasi Variabel

In [16]:
df_alt = pd.read_csv ('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_player.csv')
alt = df_alt['ID Pemain']
alternatif = alt.to_numpy()
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [17]:
kriteria = ['c1','c2','c3','c4','c5','c6','c7','c8']
costbenefit = ['benefit','benefit','benefit','benefit','benefit','benefit','benefit','benefit']
kepentingan = [3,3,4,4,3,2,1,4]
alternatifkriteria = df_alt[['C1','C2','C3','C4','C5','C6','C7','C8']].to_numpy()
alternatifkriteria

array([[ 20,  20,  20,  20,  20,  20,  20,  20],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 101,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [18]:
print(str(kriteria))
print(str(costbenefit))
print(str(kepentingan))
print(str(alternatifkriteria))

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8']
['benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit']
[3, 3, 4, 4, 3, 2, 1, 4]
[[ 20  20  20  20  20  20  20  20]
 [ 60  40  40  40  60  60  40  60]
 [ 80  60  80  80  80  80  80  80]
 [ 21  60  21  21  21  21  21  21]
 [ 61 100  41  41  61  61  41  61]
 [ 81  21  81  81  81  81  81  81]
 [ 22  41  22  22  22  22  22  22]
 [ 62  61  42  42  62  62  42  62]
 [ 82  61  82  82  82  82  82  82]
 [ 23 101  23  23  23  23  23  23]
 [ 21  22  21  21  21  21  21  21]
 [ 61  42  41  41  61  61  41  61]
 [ 81  62  81  81  81  81  81  81]
 [ 22  62  22  22  22  22  22  22]
 [ 62 100  42  42  62  62  42  62]
 [ 82  23  82  82  82  82  82  82]
 [ 23  43  23  23  23  23  23  23]
 [ 63  63  43  43  63  63  43  63]
 [ 83  63  83  83  83  83  83  83]
 [ 24 100  24  24  24  24  24  24]
 [ 22  24  22  22  22  22  22  22]
 [ 62  44  42  42  62  62  42  62]
 [ 82  64  82  82  82  82  82  82]
 [ 23  64  23  23  23  23  23  2

## Memasukan Rumus SAW

In [19]:
pembagi = []
for i in range(len(kriteria)):
    pembagi.append(0)
    for j in range(len(alternatif)):
        if costbenefit[i] == 'cost':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] > alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] < alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]

In [20]:
print(str(pembagi))

[91, 101, 91, 91, 91, 91, 91, 91]


## Tahap Normalisasi

In [21]:
normalisasi = []
for i in range(len(alternatif)):
    normalisasi.append([])
    for j in range(len(kriteria)):
        normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            normalisasi[i][j] = pembagi[j] / alternatifkriteria[i][j]
        else: #if costbenefit[j] == 'benefit':
            normalisasi[i][j] = alternatifkriteria[i][j] / pembagi[j]
            
print(str(normalisasi))

[[0.21978021978021978, 0.19801980198019803, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978], [0.6593406593406593, 0.39603960396039606, 0.43956043956043955, 0.43956043956043955, 0.6593406593406593, 0.6593406593406593, 0.43956043956043955, 0.6593406593406593], [0.8791208791208791, 0.594059405940594, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791], [0.23076923076923078, 0.594059405940594, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078], [0.6703296703296703, 0.9900990099009901, 0.45054945054945056, 0.45054945054945056, 0.6703296703296703, 0.6703296703296703, 0.45054945054945056, 0.6703296703296703], [0.8901098901098901, 0.2079207920792079, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901], [0.2417

## Hasil Skor/Nilai Pemain

In [22]:
hasil = []
for i in range(len(alternatif)):
    hasil.append(0)
    for j in range(len(kriteria)):
        hasil[i] = hasil[i] + (normalisasi[i][j] * kepentingan[j])
        
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [23]:
print(str(hasil))

[5.20944402132521, 13.056250680013056, 20.24371667936024, 6.62833206397563, 15.06919812860407, 19.316070068545315, 6.2947448591012956, 14.141551517789143, 20.734958111195738, 8.307692307692307, 5.499619192688501, 13.346425851376347, 20.533891850723535, 6.918507235338919, 15.299967359373301, 19.60624523990861, 6.584920030464585, 14.43172668915243, 21.025133282559025, 8.508758568164508, 5.78979436405179, 13.636601022739637, 20.824067022086826, 7.208682406702208, 15.530736590142531, 19.896420411271897, 6.875095201827874, 14.721901860515723, 21.31530845392232, 8.73952779893374, 6.07996953541508, 13.926776194102928, 21.114242193450117, 7.498857578065498, 15.761505820911763, 20.18659558263519, 7.165270373191165, 15.012077031879013, 21.605483625285608, 8.97029702970297, 6.37014470677837, 14.216951365466219, 21.40441736481341, 7.789032749428788, 15.992275051680993, 20.47677075399848, 7.455445544554454, 15.302252203242302, 21.8956587966489, 9.201066260472201, 6.66031987814166, 14.50712653682950

## Pembentukan Kategori

In [24]:
data_skor = ({'ID_Pemain':(alternatif),'nilai':(hasil)})
df_skor = pd.DataFrame(data_skor)

In [25]:
df_n = df_skor['nilai']
n =  df_n.to_numpy()
ktr = []
def hasil():
    for i in n:
        if i < 9:
            ktr.append('pemula')
        elif i >= 9 and i <= 17:
            ktr.append('menengah')
        else :
            ktr.append('ahli')

hasil()

In [26]:
df_skor.insert(2, 'kategori', ktr, True)
display(df_skor)

ID_Pemain      nilai  kategori
0       25601   5.209444    pemula
1       25602  13.056251  menengah
2       25603  20.243717      ahli
3       25604   6.628332    pemula
4       25605  15.069198  menengah
..        ...        ...       ...
95      25696  21.927647      ahli
96      25697   8.906321    pemula
97      25698  16.753128  menengah
98      25699  23.346535      ahli
99      25700  10.354912  menengah

[100 rows x 3 columns]

In [27]:
df_skor.to_csv('data_skor_kategori_prediksi.csv')