In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Identifikasi Variabel

In [117]:
df_alt = pd.read_csv ('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_player.csv')

In [118]:
alt = df_alt['ID Pemain']

In [119]:
alternatif = alt.to_numpy()

In [120]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [121]:
kriteria = ['c1','c2','c3','c4','c5','c6','c7','c8']

In [122]:
costbenefit = ['benefit','benefit','benefit','benefit','benefit','benefit','benefit','benefit']

In [123]:
kepentingan = [3,3,4,4,3,2,1,4]

In [124]:
alternatifkriteria = df_alt[['C1','C2','C3','C4','C5','C6','C7','C8']].to_numpy()
alternatifkriteria

array([[ 20,  20,  20,  20,  20,  20,  20,  20],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 101,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [125]:
print(str(kriteria))

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8']


In [126]:
print(str(costbenefit))

['benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit']


In [127]:
print(str(kepentingan))

[3, 3, 4, 4, 3, 2, 1, 4]


In [128]:
print(str(alternatifkriteria))

[[ 20  20  20  20  20  20  20  20]
 [ 60  40  40  40  60  60  40  60]
 [ 80  60  80  80  80  80  80  80]
 [ 21  60  21  21  21  21  21  21]
 [ 61 100  41  41  61  61  41  61]
 [ 81  21  81  81  81  81  81  81]
 [ 22  41  22  22  22  22  22  22]
 [ 62  61  42  42  62  62  42  62]
 [ 82  61  82  82  82  82  82  82]
 [ 23 101  23  23  23  23  23  23]
 [ 21  22  21  21  21  21  21  21]
 [ 61  42  41  41  61  61  41  61]
 [ 81  62  81  81  81  81  81  81]
 [ 22  62  22  22  22  22  22  22]
 [ 62 100  42  42  62  62  42  62]
 [ 82  23  82  82  82  82  82  82]
 [ 23  43  23  23  23  23  23  23]
 [ 63  63  43  43  63  63  43  63]
 [ 83  63  83  83  83  83  83  83]
 [ 24 100  24  24  24  24  24  24]
 [ 22  24  22  22  22  22  22  22]
 [ 62  44  42  42  62  62  42  62]
 [ 82  64  82  82  82  82  82  82]
 [ 23  64  23  23  23  23  23  23]
 [ 63 100  43  43  63  63  43  63]
 [ 83  25  83  83  83  83  83  83]
 [ 24  45  24  24  24  24  24  24]
 [ 64  65  44  44  64  64  44  64]
 [ 84  65  84  84  8

In [129]:
pembagi = []

In [130]:
for i in range(len(kriteria)):
    pembagi.append(0)
    for j in range(len(alternatif)):
        if costbenefit[i] == 'cost':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] > alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] < alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]

In [131]:
print(str(pembagi))

[91, 101, 91, 91, 91, 91, 91, 91]


## Tahap Normalisasi

In [132]:
normalisasi = []

In [133]:
for i in range(len(alternatif)):
    normalisasi.append([])
    for j in range(len(kriteria)):
        normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            normalisasi[i][j] = pembagi[j] / alternatifkriteria[i][j]
        else: #if costbenefit[j] == 'benefit':
            normalisasi[i][j] = alternatifkriteria[i][j] / pembagi[j]

In [134]:
print(str(normalisasi))

[[0.21978021978021978, 0.19801980198019803, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978, 0.21978021978021978], [0.6593406593406593, 0.39603960396039606, 0.43956043956043955, 0.43956043956043955, 0.6593406593406593, 0.6593406593406593, 0.43956043956043955, 0.6593406593406593], [0.8791208791208791, 0.594059405940594, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791, 0.8791208791208791], [0.23076923076923078, 0.594059405940594, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078, 0.23076923076923078], [0.6703296703296703, 0.9900990099009901, 0.45054945054945056, 0.45054945054945056, 0.6703296703296703, 0.6703296703296703, 0.45054945054945056, 0.6703296703296703], [0.8901098901098901, 0.2079207920792079, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901, 0.8901098901098901], [0.2417

In [135]:
hasil = []

In [136]:
for i in range(len(alternatif)):
    hasil.append(0)
    for j in range(len(kriteria)):
        hasil[i] = hasil[i] + (normalisasi[i][j] * kepentingan[j])

## Hasil Skor Nilai

In [137]:
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [138]:
print(str(hasil))

[5.20944402132521, 13.056250680013056, 20.24371667936024, 6.62833206397563, 15.06919812860407, 19.316070068545315, 6.2947448591012956, 14.141551517789143, 20.734958111195738, 8.307692307692307, 5.499619192688501, 13.346425851376347, 20.533891850723535, 6.918507235338919, 15.299967359373301, 19.60624523990861, 6.584920030464585, 14.43172668915243, 21.025133282559025, 8.508758568164508, 5.78979436405179, 13.636601022739637, 20.824067022086826, 7.208682406702208, 15.530736590142531, 19.896420411271897, 6.875095201827874, 14.721901860515723, 21.31530845392232, 8.73952779893374, 6.07996953541508, 13.926776194102928, 21.114242193450117, 7.498857578065498, 15.761505820911763, 20.18659558263519, 7.165270373191165, 15.012077031879013, 21.605483625285608, 8.97029702970297, 6.37014470677837, 14.216951365466219, 21.40441736481341, 7.789032749428788, 15.992275051680993, 20.47677075399848, 7.455445544554454, 15.302252203242302, 21.8956587966489, 9.201066260472201, 6.66031987814166, 14.50712653682950

## Tabel Skor Nilai

In [139]:
data_skor = ({'ID_Pemain':(alternatif),'nilai':(hasil)})

In [140]:
df_skor = pd.DataFrame(data_skor)
display(df_skor)

ID_Pemain      nilai
0       25601   5.209444
1       25602  13.056251
2       25603  20.243717
3       25604   6.628332
4       25605  15.069198
..        ...        ...
95      25696  21.927647
96      25697   8.906321
97      25698  16.753128
98      25699  23.346535
99      25700  10.354912

[100 rows x 2 columns]

## Kesimpulan jika nilai < 9 (pemula), 9-17(menengah), dan >17(ahli)

In [141]:
df_skor[df_skor["nilai"] < 9]

ID_Pemain     nilai
0       25601  5.209444
3       25604  6.628332
6       25607  6.294745
9       25610  8.307692
10      25611  5.499619
13      25614  6.918507
16      25617  6.584920
19      25620  8.508759
20      25621  5.789794
23      25624  7.208682
26      25627  6.875095
29      25630  8.739528
30      25631  6.079970
33      25634  7.498858
36      25637  7.165270
39      25640  8.970297
40      25641  6.370145
43      25644  7.789033
46      25647  7.455446
50      25651  6.660320
53      25654  8.079208
56      25657  7.745621
60      25661  6.950495
63      25664  8.369383
66      25667  8.035796
70      25671  7.240670
73      25674  8.659558
76      25677  8.325971
80      25681  7.530845
83      25684  8.949733
86      25687  8.616146
90      25691  7.821021
96      25697  8.906321

In [142]:
df_skor[df_skor["nilai"] > 17]
df_skor

ID_Pemain      nilai
0       25601   5.209444
1       25602  13.056251
2       25603  20.243717
3       25604   6.628332
4       25605  15.069198
..        ...        ...
95      25696  21.927647
96      25697   8.906321
97      25698  16.753128
98      25699  23.346535
99      25700  10.354912

[100 rows x 2 columns]

In [143]:
# df_skor[df_skor["nilai"] 9 < 17]

In [144]:
kesimpulan = []

In [145]:
# for i in range(len(nilai)):
#     kesimpulan.append(2)
#     for j in range(len(nilai)):
#         if costbenefit[i] == < 9:
#             if j == 0:
#                 [i] = alternatifkriteria[j][i]
#             else:
#                 if pembagi[i] > alternatifkriteria[j][i]:
#                     pembagi[i] = alternatifkriteria[j][i]
#         else: #if costbenefit[i] == 'benefit':
#             if j == 0:
#                 pembagi[i] = alternatifkriteria[j][i]
#             else:
#                 if pembagi[i] < alternatifkriteria[j][i]:
#                     pembagi[i] = alternatifkriteria[j][i]

## Hitung Akurasi

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

## Membagi data x_test dan y_test

In [148]:
xalt = df_alt.loc[0:49, 'ID Pemain']
x_alt = xalt.to_numpy()

In [149]:
x = df_alt.loc[0:49, 'C1':'C8']
x_test = x.to_numpy()
x_test

array([[ 20,  20,  20,  20,  20,  20,  20,  20],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 101,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [150]:
yalt = df_alt.loc[0:49, 'ID Pemain']
y_alt = yalt.to_numpy()
y = df_alt.loc[50:100, 'C1':'C8']
y_test = y.to_numpy()
y_test

array([[ 25,  30,  25,  25,  25,  25,  25,  25],
       [ 65,  50,  45,  45,  65,  65,  45,  65],
       [ 85,  70,  85,  85,  85,  85,  85,  85],
       [ 26,  70,  26,  26,  26,  26,  26,  26],
       [ 66, 100,  46,  46,  66,  66,  46,  66],
       [ 86,  31,  86,  86,  86,  86,  86,  86],
       [ 27,  51,  27,  27,  27,  27,  27,  27],
       [ 67,  71,  47,  47,  67,  67,  47,  67],
       [ 87,  71,  87,  87,  87,  87,  87,  87],
       [ 28, 100,  28,  28,  28,  28,  28,  28],
       [ 26,  32,  26,  26,  26,  26,  26,  26],
       [ 66,  52,  46,  46,  66,  66,  46,  66],
       [ 86,  72,  86,  86,  86,  86,  86,  86],
       [ 27,  72,  27,  27,  27,  27,  27,  27],
       [ 67, 100,  47,  47,  67,  67,  47,  67],
       [ 87,  33,  87,  87,  87,  87,  87,  87],
       [ 28,  53,  28,  28,  28,  28,  28,  28],
       [ 68,  73,  48,  48,  68,  68,  48,  68],
       [ 88,  73,  88,  88,  88,  88,  88,  88],
       [ 29, 100,  29,  29,  29,  29,  29,  29],
       [ 27,  34,  2

In [155]:
x_pembagi = []

In [156]:
for i in range(len(kriteria)):
    x_pembagi.append(0)
    for j in range(len(x_alt)):
        if costbenefit[i] == 'cost':
            if j == 0:
                x_pembagi[i] = x_test[j][i]
            else:
                if x_pembagi[i] > x_test[j][i]:
                    x_pembagi[i] = x_test[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                x_pembagi[i] = x_test[j][i]
            else:
                if x_pembagi[i] < x_test[j][i]:
                    x_pembagi[i] = x_test[j][i]

In [157]:
print(str(x_pembagi))

[86, 101, 86, 86, 86, 86, 86, 86]


In [158]:
y_pembagi = []

In [159]:
for i in range(len(kriteria)):
    y_pembagi.append(0)
    for j in range(len(x_alt)):
        if costbenefit[i] == 'cost':
            if j == 0:
                y_pembagi[i] = x_test[j][i]
            else:
                if y_pembagi[i] > x_test[j][i]:
                    y_pembagi[i] = x_test[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                y_pembagi[i] = x_test[j][i]
            else:
                if y_pembagi[i] < x_test[j][i]:
                    y_pembagi[i] = x_test[j][i]

In [160]:
x_normalisasi = []

In [169]:
for i in range(len(x_alt)):
    x_normalisasi.append([])
    for j in range(len(kriteria)):
        x_normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            x_normalisasi[i][j] = x_pembagi[j] / x_test[i][j]
        else: #if costbenefit[j] == 'benefit':
            x_normalisasi[i][j] = x_test[i][j] / x_pembagi[j]

In [170]:
y_normalisasi = []

In [171]:
for i in range(len(y_alt)):
    y_normalisasi.append([])
    for j in range(len(kriteria)):
        y_normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            y_normalisasi[i][j] = y_pembagi[j] / y_test[i][j]
        else: #if costbenefit[j] == 'benefit':
            y_normalisasi[i][j] = y_test[i][j] / y_pembagi[j]

In [164]:
x_hasil = []

In [165]:
for i in range(len(x_test)):
    x_hasil.append(0)
    for j in range(len(kriteria)):
        x_hasil[i] = x_hasil[i] + (x_normalisasi[i][j] * kepentingan[j])

In [174]:
y_hasil = []

In [175]:
for i in range(len(y_test)):
    y_hasil.append(0)
    for j in range(len(kriteria)):
        y_hasil[i] = y_hasil[i] + (y_normalisasi[i][j] * kepentingan[j])

In [166]:
x_pred = ({'ID Pemain':(x_alt),'nilai':(x_hasil)})

In [167]:
df_x_pred = pd.DataFrame(x_pred)
display(df_x_pred)

ID Pemain      nilai
0       25601   5.477780
1       25602  13.746258
2       25603  21.317062
3       25604   6.910085
4       25605  15.772623
5       25606  20.402832
6       25607   6.589915
7       25608  14.858393
8       25609  21.835137
9       25610   8.616279
10      25611   5.781372
11      25612  14.049850
12      25613  21.620654
13      25614   7.213677
14      25615  16.016809
15      25616  20.706424
16      25617   6.893507
17      25618  15.161985
18      25619  22.138729
19      25620   8.830762
20      25621   6.084964
21      25622  14.353442
22      25623  21.924246
23      25624   7.517269
24      25625  16.260995
25      25626  21.010016
26      25627   7.197099
27      25628  15.465577
28      25629  22.442321
29      25630   9.074948
30      25631   6.388556
31      25632  14.657034
32      25633  22.227838
33      25634   7.820861
34      25635  16.505181
35      25636  21.313608
36      25637   7.500691
37      25638  15.769169
38      25639  22.745913
39      25640   9.319134
40      25641   6.692148
41      25642  14.960626
42      25643  22.531430
43      25644   8.124453
44      25645  16.749367
45      25646  21.617200
46      25647   7.804283
47      25648  16.072761
48      25649  23.049505
49      25650   9.563320

In [177]:
y_pred = ({'ID Pemain':(y_alt),'nilai':(y_hasil)})

In [178]:
df_y_pred = pd.DataFrame(y_pred)
display(df_y_pred)

ID Pemain      nilai
0       25601   6.995740
1       25602  15.264218
2       25603  22.835022
3       25604   8.428045
4       25605  16.993553
5       25606  21.920792
6       25607   8.107875
7       25608  16.376353
8       25609  23.353097
9       25610   9.807506
10      25611   7.299332
11      25612  15.567810
12      25613  23.138614
13      25614   8.731637
14      25615  17.237739
15      25616  22.224384
16      25617   8.411467
17      25618  16.679945
18      25619  23.656689
19      25620  10.051692
20      25621   7.602924
21      25622  15.871402
22      25623  23.442206
23      25624   9.035229
24      25625  17.481925
25      25626  22.527976
26      25627   8.715059
27      25628  16.983537
28      25629  23.960281
29      25630  10.295878
30      25631   7.906516
31      25632  16.174994
32      25633  23.745798
33      25634   9.338821
34      25635  17.726111
35      25636  22.831568
36      25637   9.018651
37      25638  17.287129
38      25639  24.263873
39      25640  10.540064
40      25641   8.210108
41      25642  16.478586
42      25643  24.049390
43      25644   9.642413
44      25645  17.970297
45      25646  23.135160
46      25647   9.322243
47      25648  17.590721
48      25649  24.567465
49      25650  10.784251

In [179]:
df_alt

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
0       25601  20   20  20  20  20  20  20  20    20
1       25602  60   40  40  40  60  60  40  60    60
2       25603  80   60  80  80  80  80  80  80    80
3       25604  21   60  21  21  21  21  21  21    21
4       25605  61  100  41  41  61  61  41  61    61
..        ...  ..  ...  ..  ..  ..  ..  ..  ..   ...
95      25696  90   39  90  90  90  90  90  90    90
96      25697  31   59  31  31  31  31  31  31    31
97      25698  71   79  51  51  71  71  51  71    71
98      25699  91   79  91  91  91  91  91  91    91
99      25700  32  100  32  32  32  32  32  32    32

[100 rows x 10 columns]

In [242]:
df_alt.shape

(100, 10)

In [251]:
proposisi = 0.7
df_1 = df_alt.sample(frac=proposisi)
df_2 = df_alt.drop(df_1.index)

print (f'df_1 shape = {df_1.shape}')
print (f'df_2 shape = {df_2.shape}')

df_1 shape = (70, 10)
df_2 shape = (30, 10)


In [252]:
df_1

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
81      25682  68   56  48  48  68  68  48  68    68
3       25604  21   60  21  21  21  21  21  21    21
29      25630  25  100  25  25  25  25  25  25    25
43      25644  25   68  25  25  25  25  25  25    25
33      25634  24   66  24  24  24  24  24  24    24
..        ...  ..  ...  ..  ..  ..  ..  ..  ..   ...
21      25622  62   44  42  42  62  62  42  62    62
67      25668  68   73  48  48  68  68  48  68    68
73      25674  28   74  28  28  28  28  28  28    28
0       25601  20   20  20  20  20  20  20  20    20
78      25679  89   75  89  89  89  89  89  89    89

[70 rows x 10 columns]

In [253]:
df_2

ID Pemain  C1   C2  C3  C4  C5  C6  C7  C8  C1.1
1       25602  60   40  40  40  60  60  40  60    60
5       25606  81   21  81  81  81  81  81  81    81
6       25607  22   41  22  22  22  22  22  22    22
9       25610  23  101  23  23  23  23  23  23    23
14      25615  62  100  42  42  62  62  42  62    62
22      25623  82   64  82  82  82  82  82  82    82
25      25626  83   25  83  83  83  83  83  83    83
27      25628  64   65  44  44  64  64  44  64    64
28      25629  84   65  84  84  84  84  84  84    84
31      25632  63   46  43  43  63  63  43  63    63
36      25637  25   47  25  25  25  25  25  25    25
38      25639  85   67  85  85  85  85  85  85    85
39      25640  26  100  26  26  26  26  26  26    26
40      25641  24   28  24  24  24  24  24  24    24
46      25647  26   49  26  26  26  26  26  26    26
47      25648  66   69  46  46  66  66  46  66    66
51      25652  65   50  45  45  65  65  45  65    65
52      25653  85   70  85  85  85  85  85  85    85
62      25663  86   72  86  86  86  86  86  86    86
65      25666  87   33  87  87  87  87  87  87    87
72      25673  87   74  87  87  87  87  87  87    87
82      25683  88   76  88  88  88  88  88  88    88
83      25684  29   76  29  29  29  29  29  29    29
84      25685  69  100  49  49  69  69  49  69    69
85      25686  89   37  89  89  89  89  89  89    89
87      25688  70   77  50  50  70  70  50  70    70
89      25690  31  100  31  31  31  31  31  31    31
91      25692  69   58  49  49  69  69  49  69    69
93      25694  30   78  30  30  30  30  30  30    30
94      25695  70  100  50  50  70  70  50  70    70