# Data Pemain Game Mobile Legends Aktual

## Menambahkan Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Mengidentifikasi Variabel

In [2]:
df_alt = pd.read_csv ('/home/adamyunian/Desktop/python_code/simple_additive_weight/data_player_aktual.csv')
alt = df_alt['ID Pemain']
alternatif = alt.to_numpy()
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [3]:
kriteria = ['c1','c2','c3','c4','c5','c6','c7','c8']
costbenefit = ['benefit','benefit','benefit','benefit','benefit','benefit','benefit','benefit']
kepentingan = [3,3,4,4,3,2,1,4]
alternatifkriteria = df_alt[['C1','C2','C3','C4','C5','C6','C7','C8']].to_numpy()
alternatifkriteria

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [ 60,  40,  40,  40,  60,  60,  40,  60],
       [ 80,  60,  80,  80,  80,  80,  80,  80],
       [ 21,  60,  21,  21,  21,  21,  21,  21],
       [ 61, 100,  41,  41,  61,  61,  41,  61],
       [ 81,  21,  81,  81,  81,  81,  81,  81],
       [ 22,  41,  22,  22,  22,  22,  22,  22],
       [ 62,  61,  42,  42,  62,  62,  42,  62],
       [ 82,  61,  82,  82,  82,  82,  82,  82],
       [ 23, 100,  23,  23,  23,  23,  23,  23],
       [ 21,  22,  21,  21,  21,  21,  21,  21],
       [ 61,  42,  41,  41,  61,  61,  41,  61],
       [ 81,  62,  81,  81,  81,  81,  81,  81],
       [ 22,  62,  22,  22,  22,  22,  22,  22],
       [ 62, 100,  42,  42,  62,  62,  42,  62],
       [ 82,  23,  82,  82,  82,  82,  82,  82],
       [ 23,  43,  23,  23,  23,  23,  23,  23],
       [ 63,  63,  43,  43,  63,  63,  43,  63],
       [ 83,  63,  83,  83,  83,  83,  83,  83],
       [ 24, 100,  24,  24,  24,  24,  24,  24],
       [ 22,  24,  2

In [4]:
print(str(kriteria))
print(str(costbenefit))
print(str(kepentingan))
print(str(alternatifkriteria))

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8']
['benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit', 'benefit']
[3, 3, 4, 4, 3, 2, 1, 4]
[[100 100 100 100 100 100 100 100]
 [ 60  40  40  40  60  60  40  60]
 [ 80  60  80  80  80  80  80  80]
 [ 21  60  21  21  21  21  21  21]
 [ 61 100  41  41  61  61  41  61]
 [ 81  21  81  81  81  81  81  81]
 [ 22  41  22  22  22  22  22  22]
 [ 62  61  42  42  62  62  42  62]
 [ 82  61  82  82  82  82  82  82]
 [ 23 100  23  23  23  23  23  23]
 [ 21  22  21  21  21  21  21  21]
 [ 61  42  41  41  61  61  41  61]
 [ 81  62  81  81  81  81  81  81]
 [ 22  62  22  22  22  22  22  22]
 [ 62 100  42  42  62  62  42  62]
 [ 82  23  82  82  82  82  82  82]
 [ 23  43  23  23  23  23  23  23]
 [ 63  63  43  43  63  63  43  63]
 [ 83  63  83  83  83  83  83  83]
 [ 24 100  24  24  24  24  24  24]
 [ 22  24  22  22  22  22  22  22]
 [ 62  44  42  42  62  62  42  62]
 [ 82  64  82  82  82  82  82  82]
 [ 23  64  23  23  23  23  23  2

## Memasukan Rumus SAW

In [5]:
pembagi = []
for i in range(len(kriteria)):
    pembagi.append(0)
    for j in range(len(alternatif)):
        if costbenefit[i] == 'cost':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] > alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]
        else: #if costbenefit[i] == 'benefit':
            if j == 0:
                pembagi[i] = alternatifkriteria[j][i]
            else:
                if pembagi[i] < alternatifkriteria[j][i]:
                    pembagi[i] = alternatifkriteria[j][i]

In [6]:
print(str(pembagi))

[100, 100, 100, 100, 100, 100, 100, 100]


## Tahap Normalisasi

In [7]:
normalisasi = []
for i in range(len(alternatif)):
    normalisasi.append([])
    for j in range(len(kriteria)):
        normalisasi[i].append(0)
        if costbenefit[j] == 'cost':
            normalisasi[i][j] = pembagi[j] / alternatifkriteria[i][j]
        else: #if costbenefit[j] == 'benefit':
            normalisasi[i][j] = alternatifkriteria[i][j] / pembagi[j]
            
print(str(normalisasi))

[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.6, 0.4, 0.4, 0.4, 0.6, 0.6, 0.4, 0.6], [0.8, 0.6, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8], [0.21, 0.6, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21], [0.61, 1.0, 0.41, 0.41, 0.61, 0.61, 0.41, 0.61], [0.81, 0.21, 0.81, 0.81, 0.81, 0.81, 0.81, 0.81], [0.22, 0.41, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22], [0.62, 0.61, 0.42, 0.42, 0.62, 0.62, 0.42, 0.62], [0.82, 0.61, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82], [0.23, 1.0, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23], [0.21, 0.22, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21], [0.61, 0.42, 0.41, 0.41, 0.61, 0.61, 0.41, 0.61], [0.81, 0.62, 0.81, 0.81, 0.81, 0.81, 0.81, 0.81], [0.22, 0.62, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22], [0.62, 1.0, 0.42, 0.42, 0.62, 0.62, 0.42, 0.62], [0.82, 0.23, 0.82, 0.82, 0.82, 0.82, 0.82, 0.82], [0.23, 0.43, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23], [0.63, 0.63, 0.43, 0.43, 0.63, 0.63, 0.43, 0.63], [0.83, 0.63, 0.83, 0.83, 0.83, 0.83, 0.83, 0.83], [0.24, 1.0, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24], [0.22, 0.24, 0.22, 0.22, 0.2

## Hasil Skor/Nilai Pemain

In [8]:
hasil = []
for i in range(len(alternatif)):
    hasil.append(0)
    for j in range(len(kriteria)):
        hasil[i] = hasil[i] + (normalisasi[i][j] * kepentingan[j])
        
print(str(alternatif))

[25601 25602 25603 25604 25605 25606 25607 25608 25609 25610 25611 25612
 25613 25614 25615 25616 25617 25618 25619 25620 25621 25622 25623 25624
 25625 25626 25627 25628 25629 25630 25631 25632 25633 25634 25635 25636
 25637 25638 25639 25640 25641 25642 25643 25644 25645 25646 25647 25648
 25649 25650 25651 25652 25653 25654 25655 25656 25657 25658 25659 25660
 25661 25662 25663 25664 25665 25666 25667 25668 25669 25670 25671 25672
 25673 25674 25675 25676 25677 25678 25679 25680 25681 25682 25683 25684
 25685 25686 25687 25688 25689 25690 25691 25692 25693 25694 25695 25696
 25697 25698 25699 25700]


In [9]:
print(str(hasil))

[24.0, 12.0, 18.6, 6.209999999999999, 14.01, 17.64, 5.85, 13.05, 19.05, 7.830000000000001, 5.069999999999999, 12.27, 18.87, 6.48, 14.219999999999999, 17.91, 6.12, 13.319999999999999, 19.32, 8.04, 5.34, 12.54, 19.14, 6.750000000000001, 14.43, 18.18, 6.39, 13.589999999999998, 19.59, 8.25, 5.61, 12.809999999999999, 19.41, 7.0200000000000005, 14.639999999999999, 18.45, 6.66, 13.860000000000001, 19.86, 8.46, 5.88, 13.08, 19.68, 7.29, 14.85, 18.72, 6.930000000000001, 14.13, 20.130000000000003, 8.670000000000002, 6.15, 13.35, 19.95, 7.56, 15.060000000000002, 18.99, 7.200000000000001, 14.4, 20.400000000000002, 8.88, 6.420000000000001, 13.620000000000001, 20.220000000000002, 7.830000000000002, 15.27, 19.259999999999998, 7.470000000000001, 14.67, 20.669999999999998, 9.09, 6.690000000000001, 13.89, 20.490000000000002, 8.1, 15.479999999999999, 19.53, 7.74, 14.940000000000001, 20.94, 9.299999999999999, 6.960000000000001, 14.160000000000002, 20.759999999999998, 8.370000000000001, 15.690000000000001,

## Pembentukan Kategori

In [10]:
data_skor = ({'ID_Pemain':(alternatif),'nilai':(hasil)})
df_skor = pd.DataFrame(data_skor)

In [11]:
df_n = df_skor['nilai']
n =  df_n.to_numpy()
ktr = []
def hasil():
    for i in n:
        if i < 9:
            ktr.append('pemula')
        elif i >= 9 and i <= 17:
            ktr.append('menengah')
        else :
            ktr.append('ahli')

hasil()

In [12]:
df_skor.insert(2, 'kategori', ktr, True)
display(df_skor)

ID_Pemain  nilai  kategori
0       25601  24.00      ahli
1       25602  12.00  menengah
2       25603  18.60      ahli
3       25604   6.21    pemula
4       25605  14.01  menengah
..        ...    ...       ...
95      25696  20.07      ahli
96      25697   8.28    pemula
97      25698  15.48  menengah
98      25699  21.48      ahli
99      25700   9.72  menengah

[100 rows x 3 columns]

In [13]:
df_skor.to_csv('data_skor_kategori_aktual.csv')